services:
  redis:
    image: redislabs/redismod
    container_name: redis_discofy
    ports:
      - '6379:6379'
  flask:
    build: .
    container_name: flask_discofy
    environment:
      - PORT=5000
      - PYTHONPATH=/App
    ports:
      - '5000:5000'
    env_file: .env
    depends_on:
      - redis
